version: '3.9'

services:
  postgres:
    image: postgres:16.4-bullseye
    container_name: postgres
    restart: unless-stopped
    env_file:
      - envs/.env.docker.postgres.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev: