version: '3.9'

services:
  app:
    build: .
    image: price-tune:dev
    container_name: price-tune
    depends_on:
      - postgres
    env_file:
      - envs/.env.dev
    expose:
      - "8000"
    volumes:
      - price-tune-static:/opt/app/static
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.template.conf:/etc/nginx/nginx.template.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - price-tune-static:/opt/app/static
    env_file:
      - envs/.env.docker.nginx.dev
    restart: unless-stopped
    command: /bin/sh -c "envsubst '$$SERVER_NAME' < /etc/nginx/nginx.template.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

  postgres:
    image: postgres:16.4-bullseye
    container_name: postgres
    env_file:
      - envs/.env.docker.postgres.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data_dev:
  price-tune-static_dev: