# Generated by Django 5.1.2 on 2024-10-18 01:18

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_groupproduct_level_groupproduct_lft_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupproduct",
            name="idx",
            field=models.PositiveIntegerField(default=1, help_text="Индекс сортировки группового продукта"),
        ),
        migrations.AlterField(
            model_name="product",
            name="group",
            field=mptt.fields.TreeForeignKey(
                help_text="Группа продукта",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="product.groupproduct",
            ),
        ),
    ]
